"""init

Revision ID: b8811e1dfbd5
Revises: 
Create Date: 2024-02-03 20:20:14.273005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8811e1dfbd5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('payments',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('credits', sa.Float(), nullable=False),
    sa.Column('balance_total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('requests',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('source_file_size', sa.Float(), nullable=False),
    sa.Column('result_file_size', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('tickets',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('requests')
    op.drop_table('payments')
    op.drop_table('users')
    # ### end Alembic commands ###
